---
- name: restart containerd service
  service:
    name: containerd
    state: restarted
  listen: "restart containerd"

- name: restart kubelet service
  service:
    name: kubelet
    state: restarted
  listen: "restart kubelet"