---
- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name:  create join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}" 

- name: join workers to cluster
  shell: "{{ join_command }} >> node_joined.log"
  args:
    chdir: /root
    creates: node_joined.log
    
    