---
- name: Downloadingcontainerd archive
  get_url:
    url: https://github.com/containerd/containerd/releases/download/v1.7.2/containerd-1.7.2-linux-amd64.tar.gz
    dest: /root/containerd/containerd.tar.gz
    mode: 600
  tags:
    - containerd-install
    - containerd-download

- name: Unarchive containerd-download
  unarchive:
    src: /root/containerd/containerd.tar.gz
    dest: /root/containerd/
    remote_src: true
  tags:
    - containerd-install
    - containerd-unarchive

- name: copy containerd binaries to destination directory
  copy:
    src: /root/containerd/bin/{{ binary }}
    dest: /usr/local/bin/{{ binary }}
    remote_src: true
  loop: "{{ containerd_binaries }}"
  loop_control:
    loop_var: "binary"
  tags:
    - containerd-install

- name: setup containerd service
  get_url:
    url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
    dest: /usr/lib/systemd/system/containerd.service
  tags:
    - containerd-install
    - containerd-service

- name: reload systemd
  shell:
    systemctl daemon-reload
  ignore_errors: true
  tags:
    - containerd-install

- name: enable containerd service
  service:
    name: containerd
    enabled: yes
  notify: "restart containerd"
  tags:
    - containerd-install
    - containerd-restart

- name: create containerd configfile directory
  file:
    path: /etc/containerd
    state: directory
  tags:
    - containerd-install
    - containerd-config

- name: create containerd configfile
  shell:
    /usr/local/bin/containerd config default > /etc/containerd/config.toml
  tags:
    - containerd-install
    - containerd-config


    

    
    

