---
- name: Disable swap
  shell:
    swapoff -a
  
- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
 
- name: Disable SElinux
  shell:
    setenforce 0
  ignore_errors: true

- name: update SElinux configfile
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'

- name: Enable IP forwarding
  