---
- name: set ip_forward
  shell:
    echo 1 > /proc/sys/net/ipv4/ip_forward

- name: Add net.bridge.bridge-nf-call-iptables to /etc/sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    line: 'net.bridge.bridge-nf-call-iptables = 1'

- name: load br_netfilter kernel module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: reload kernal config
  shell:
    sysctl --system

# - name: set bridge-nf-call-iptables
#   sysctl:
#     name: net.bridge.bridge-nf-call-iptables
#     value: 1

# - name: set ip_forward
#   sysctl:
#     name: net.ipv4.ip_forward
#     value: 1